person/urls.py
"""tp02_django URL Configuration."""


from django.conf.urls import url
from views import *
app_name = 'person'

urlpatterns = [
    url(r'^teacher/create/$', TeacherCreate.as_view()),
    url(r'^teacher/list/$', TeacherList.as_view(), name='teacher-list'),
    url(r'^teacher/update/(?P<pk>[0-9]+)/$', TeacherUpdate.as_view(), name='teacher-update'),
    url(r'^teacher/delete/(?P<pk>[0-9]+)/$', TeacherDelete.as_view(), name='teacher-delete'),
    url(r'^login/$', Login.as_view()),
    url(r'^student/home/(?P<pk>[0-9]+)/$', HomeStudent.as_view(), name='student-home'),


]

person/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User, Group
from django.db import models
import datetime

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=30)
    postal_code = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Home(models.Model):
    street = models.CharField(max_length=30)
    number = models.CharField(max_length=30)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.city.name + ", " + self.street + ", " + self.number


class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dni = models.IntegerField()
    home = models.ForeignKey(Home, on_delete=models.CASCADE)


    def __str__(self):
        return self.user.username


class Teacher(Person):
    degree = models.CharField(max_length=30)


class Student(Person):
    file = models.IntegerField()


class Course(models.Model):
    name = models.CharField(max_length=30)
    start_date = models.DateField(default=datetime.date.today())
    end_date = models.DateField(default=datetime.date.today())
    student = models.ManyToManyField(Student)
    teacher = models.ManyToManyField(Teacher)


    def __str__(self):
        return self.name


class Career(models.Model):
    name = models.CharField(max_length=30)
    student = models.ManyToManyField(Student)


    def __str__(self):
        return self.name

person/forms.py
# -*- coding: utf-8 -*-
from django import forms
from person.models import *


class TeacherCreateForm(forms.Form):


    def __init__(self, values):
        self.name = values.get('name', None)
        self.surname = values.get('surname', None)
        self.dni = values.get('dni', None)
        self.home = values.get('home', None)
        self.degree = values.get('degree', None)
        self.error = ""


    def is_valid(self):
        if self.name and self.surname and self.dni and self.home and self.degree:
            if Teacher.objects.all().filter(dni=self.dni).count():
                self.error = "Teacher already exists with DNI"
                return False
            return True
        self.error = "Todos los campos son obligatorios"
        return False


    def save(self):
        home = Home.objects.get(pk=self.home)
        teacher = Teacher(
            name=self.name,
            surname=self.surname,
            dni=self.dni,
            home=home,
            degree=self.degree)

        teacher.save()
        return teacher


class TeacherUpdateForm(forms.Form):
    def __init__(self, values, id):
        self.name = values.get('name', None)
        self.surname = values.get('surname', None)
        self.dni = values.get('dni', None)
        self.home = values.get('home', None)
        self.degree = values.get('degree', None)
        self.id = id
        self.error = ""


    def is_valid(self):
        if self.name and self.surname and self.dni and self.home and self.degree:
            return True
        self.error = "Todos los campos son obligatorios"
        return False


    def save(self):
        home = Home.objects.get(pk=self.home)
        teacher = Teacher.objects.get(pk=self.id)
        teacher.name = self.name
        teacher.surname = self.surname
        teacher.dni = self.dni
        teacher.degree = self.degree
        teacher.home = home

        teacher.save()
        return teacher


class TeacherDeleteForm(forms.Form):
    def __init__(self, values, id):
        self.id = id
        self.error = ""


    def is_valid(self):
        if Teacher.objects.filter(pk=self.id).exists():
            return True


    def delete(self):
        Teacher.objects.filter(pk=self.id).delete()

person/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, View
from person.models import *
from person.forms import *
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from pprint import pprint


# Create your views here.


class TeacherCreate(CreateView):
    model = Teacher
    template_name = 'teacher_create.html'
    form_class = TeacherCreateForm

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request, self.template_name, ctx)


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        ctx = {}
        if form.is_valid():
            form.save()
            ctx['error'] = "Se agrego el T"
            return render(request, self.template_name, ctx)
        else:
            ctx['error'] = "Todos los campos son obligatorios"
            return render(request, self.template_name, ctx)


class TeacherUpdate(UpdateView):
    model = Teacher
    form_class = TeacherUpdateForm
    template_name = 'teacher_update.html'


    def get(self, request, *args, **kwargs):
        pk_update = kwargs['pk']
        ctx = {}
        ctx['teacher'] = Teacher.objects.get(pk=pk_update)
        return render(request, self.template_name, ctx)


    def post(self, request, *args, **kwargs):
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.save()
            ctx['error'] = "Se modifico"
            return render(request, self.template_name, ctx)
        else:
            ctx['error'] = "Todos los campos son obligatorios"
            return render(request, self.template_name, ctx)


class TeacherList(ListView):
    model = Teacher
    template_name = 'teacher_list.html'


    def get(self, request, *args, **kwargs):
        ctx = {}
        ctx['teachers'] = Teacher.objects.all()
        return render(request, self.template_name, ctx)


class TeacherDelete(DeleteView):
    model = Teacher
    template_name = 'teacher_delete.html'
    form_class = TeacherDeleteForm

    def get(self, request, *args, **kwargs):
        pk_delete = kwargs['pk']
        ctx = {}
        ctx['teacher'] = Teacher.objects.get(pk=pk_delete)
        return render(request, self.template_name, ctx)


    def post(self, request, *args, **kwargs):
        ctx = {}
        form = self.form_class(request.POST, kwargs['pk'])
        if form.is_valid():
            form.delete()
            ctx['error'] = "Se elimino"
            return HttpResponseRedirect(reverse_lazy('person:teacher-list'))


class Login(View):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request, self.template_name, ctx)


    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print user.groups.all().values_list('name', flat=True)
            if 'Teacher' in user.groups.all().values_list('name', flat=True):
                return HttpResponseRedirect(reverse_lazy('person:teacher-list'))
            elif 'Student' in user.groups.all().values_list('name', flat=True):
                print user.pk
                return HttpResponseRedirect(reverse_lazy('person:student-home', kwargs={'pk': user.pk}))


class HomeStudent(ListView):
    template_name = 'student_home.html'


    def get(self, request, *args, **kwargs):
        ctx = {}
        student = Student.objects.get(user=kwargs['pk'])
        print student
        ctx['courses'] = student.course_set.all()
        return render(request, self.template_name, ctx)

person/templates/login.html
<!DOCTYPE html>
<html>
{% block content %}
<head>
<title>Log in | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">




<meta name="robots" content="NONE,NOARCHIVE">
<style type="text/css">
:root #content > #right > .dose > .dosesingle,
:root #content > #center > .dose > .dosesingle,
:root #header + #content > #left > #rlblock_left
{ display: none !important; }</style></head>
<body class=" login" data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">Sistem log</a></h1>

        </div>
        
        
    </div>
    <!-- END Header -->
    <!-- Content -->
    <div id="content" class="colM">

<div id="content-main">



<form method="post" id="login-form">
  {% csrf_token %}
  <div class="form-row">
    
    <label class="required" for="id_username">Username:</label> <input type="text" name="username" autofocus="" required="" id="id_username" maxlength="254">
  </div>
  <div class="form-row">
    
    <label class="required" for="id_password">Password:</label> <input type="password" name="password" required="" id="id_password">
  </div>
  
  
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="Log in">
  </div>
</form>

</div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->



</body>
{% endblock %}
</html>

person/templates/student_home.html
{% extends 'login.html'%}

{% block content %}
{% if error %}
       <h2>{{ error }}</h2>
      {% endif %}
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Date Start</th> 
    <th>Date End</th>
    <th>Teacher</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% for course in courses%}
  <tr>
    	<td>{{ course.name}}</td>
    	<td>{{ course.start_date}}</td>
    	<td>{{ course.end_date}}</td>
    	<td>{{ course.teacher}}</td>
    	<td><a href="">Update</a></td>
      <td><a href="">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

person/templates/teacher_create.html
{% block content %}
    <form method="post">
    	{% csrf_token %}
    	{% if error %}
    		{{ error }}
    	{% endif %}
    	<div>
    		<label>Name:</label>
    		<input type="text" name="name">
    		<br>
    		<label>Surname:</label>
    		<input type="text" name="surname">
    		<br>
    		<label>D.N.I:</label>
    		<input type="number" name="dni">
    		<br>
    		<label>Home:</label>
    		<input type="number" value="2" name="home">
    		<br>
    		<label>Degree:</label>
    		<input type="text" name="degree">
    	</div>
    	<input type="submit" value="Save">
    </form>
{% endblock %}

person/templates/teacher_delete.html
{% extends 'login.html'%}

{% block content %}
    <form method="post">
    	{% csrf_token %}
    	{% if error %}
    		{{ error }}
    	{% endif %}
    	<div>
    		<h2>Desea eliminar {{ teacher.name }}, {{ teacher.surname}}?</h2>
    	</div>
    	<input type="submit" value="Delete">
    </form>
{% endblock %}

person/templates/teacher_list.html
{% extends 'login.html'%}

{% block content %}
{% if error %}
       <h2>{{ error }}</h2>
      {% endif %}
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Surname</th> 
    <th>DNI</th>
    <th>Home</th>
    <th>Dgree</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% for teacher in teachers%}
  <tr>
    	<td>{{ teacher.name}}</td>
    	<td>{{ teacher.surname}}</td>
    	<td>{{ teacher.dni}}</td>
    	<td>{{ teacher.home}}</td>
    	<td>{{ teacher.degree}}</td>
    	<td><a href="{% url 'person:teacher-update' teacher.pk %}">Update</a></td>
      <td><a href="{% url 'person:teacher-delete' teacher.pk %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

person/templates/teacher_update.html
{% block content %}
    <form method="post">
    	{% csrf_token %}
    	{% if error %}
    		{{ error }}
    	{% endif %}
    	<div>
    		<label>Name:</label>
    		<input type="text" value="{{teacher.name}}" name="name">
    		<br>
    		<label>Surname:</label>
    		<input type="text" value="{{teacher.surname}}" name="surname">
    		<br>
    		<label>D.N.I:</label>
    		<input type="number" value="{{teacher.dni}}" name="dni">
    		<br>
    		<label>Home:</label>
            <input type="number" value="{{teacher.home}}" name="home">
    		<br>
    		<label>Degree:</label>
    		<input type="text" value="{{teacher.degree}}" name="degree">
    	</div>
    	<input type="submit" value="Update">
    </form>
{% endblock %}